name: frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  flutter_launcher_icons: ^0.14.4
  dio: ^5.9.0
  flutter_riverpod: ^3.0.3
  flutter_dotenv: ^6.0.0
  jwt_decoder: ^2.0.1
  logger: ^2.6.2
  intl: ^0.20.2
  fl_chart: ^0.68.0
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  path: ^1.9.0
  flutter_image_compress: ^2.4.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.4
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true
